export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_LOGOUT = "USER_REGISTER_LOGOUT";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USDC_BALANCE_REQUEST = "USDC_BALANCE_REQUEST";
export const USDC_BALANCE_SUCCESS = "USDC_BALANCE_SUCCESS";
export const USDC_BALANCE_FAIL = "USDC_BALANCE_FAIL";

export const USDC_TRANSFER_REQUEST = "USDC_TRANSFER_REQUEST";
export const USDC_TRANSFER_SUCCESS = "USDC_TRANSFER_SUCCESS";
export const USDC_TRANSFER_FAIL = "USDC_TRANSFER_FAIL";

export const USDC_MINTMORE_REQUEST = "USDC_MINTMORE_REQUEST";
export const USDC_MINTMORE_SUCCESS = "USDC_MINTMORE_SUCCESS";
export const USDC_MINTMORE_FAIL = "USDC_MINTMORE_FAIL";
